### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  commentId: T:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  id: IConsoleLoggerSettings
  parent: Microsoft.Extensions.Logging.Console
  children:
  - Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken
  - Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes
  - Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload
  - Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch(System.String,Microsoft.Extensions.Logging.LogLevel@)
  langs:
  - csharp
  - vb
  name: IConsoleLoggerSettings
  nameWithType: IConsoleLoggerSettings
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  type: Interface
  source:
    remote:
      path: src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
      branch: master
      repo: https://github.com/aspnet/Logging.git
    id: IConsoleLoggerSettings
    path: ../aspnet/Logging/src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
    startLine: 5
  assemblies:
  - Microsoft.Extensions.Logging.Console
  namespace: Microsoft.Extensions.Logging.Console
  syntax:
    content: public interface IConsoleLoggerSettings
    content.vb: Public Interface IConsoleLoggerSettings
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes
  commentId: P:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes
  id: IncludeScopes
  parent: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  langs:
  - csharp
  - vb
  name: IncludeScopes
  nameWithType: IConsoleLoggerSettings.IncludeScopes
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
      branch: master
      repo: https://github.com/aspnet/Logging.git
    id: IncludeScopes
    path: ../aspnet/Logging/src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
    startLine: 7
  assemblies:
  - Microsoft.Extensions.Logging.Console
  namespace: Microsoft.Extensions.Logging.Console
  syntax:
    content: bool IncludeScopes { get; }
    content.vb: ReadOnly Property IncludeScopes As Boolean
    parameters: []
    return:
      type: System.Boolean
  overload: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken
  commentId: P:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken
  id: ChangeToken
  parent: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  langs:
  - csharp
  - vb
  name: ChangeToken
  nameWithType: IConsoleLoggerSettings.ChangeToken
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken
  type: Property
  source:
    remote:
      path: src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
      branch: master
      repo: https://github.com/aspnet/Logging.git
    id: ChangeToken
    path: ../aspnet/Logging/src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
    startLine: 9
  assemblies:
  - Microsoft.Extensions.Logging.Console
  namespace: Microsoft.Extensions.Logging.Console
  syntax:
    content: IChangeToken ChangeToken { get; }
    content.vb: ReadOnly Property ChangeToken As IChangeToken
    parameters: []
    return:
      type: Microsoft.Extensions.Primitives.IChangeToken
  overload: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch(System.String,Microsoft.Extensions.Logging.LogLevel@)
  commentId: M:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch(System.String,Microsoft.Extensions.Logging.LogLevel@)
  id: TryGetSwitch(System.String,Microsoft.Extensions.Logging.LogLevel@)
  parent: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  langs:
  - csharp
  - vb
  name: TryGetSwitch(String, out LogLevel)
  nameWithType: IConsoleLoggerSettings.TryGetSwitch(String, out LogLevel)
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch(System.String, out Microsoft.Extensions.Logging.LogLevel)
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
      branch: master
      repo: https://github.com/aspnet/Logging.git
    id: TryGetSwitch
    path: ../aspnet/Logging/src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
    startLine: 11
  assemblies:
  - Microsoft.Extensions.Logging.Console
  namespace: Microsoft.Extensions.Logging.Console
  syntax:
    content: bool TryGetSwitch(string name, out LogLevel level)
    content.vb: Function TryGetSwitch(name As String, ByRef level As LogLevel) As Boolean
    parameters:
    - id: name
      type: System.String
    - id: level
      type: Microsoft.Extensions.Logging.LogLevel
    return:
      type: System.Boolean
  overload: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch*
  nameWithType.vb: IConsoleLoggerSettings.TryGetSwitch(String, ByRef LogLevel)
  fullName.vb: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch(System.String, ByRef Microsoft.Extensions.Logging.LogLevel)
  name.vb: TryGetSwitch(String, ByRef LogLevel)
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload
  commentId: M:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload
  id: Reload
  parent: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  langs:
  - csharp
  - vb
  name: Reload()
  nameWithType: IConsoleLoggerSettings.Reload()
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload()
  type: Method
  source:
    remote:
      path: src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
      branch: master
      repo: https://github.com/aspnet/Logging.git
    id: Reload
    path: ../aspnet/Logging/src/Microsoft.Extensions.Logging.Console/IConsoleLoggerSettings.cs
    startLine: 13
  assemblies:
  - Microsoft.Extensions.Logging.Console
  namespace: Microsoft.Extensions.Logging.Console
  syntax:
    content: IConsoleLoggerSettings Reload()
    content.vb: Function Reload As IConsoleLoggerSettings
    return:
      type: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  overload: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload*
references:
- uid: Microsoft.Extensions.Logging.Console
  commentId: N:Microsoft.Extensions.Logging.Console
  isExternal: false
  name: Microsoft.Extensions.Logging.Console
  nameWithType: Microsoft.Extensions.Logging.Console
  fullName: Microsoft.Extensions.Logging.Console
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes*
  commentId: Overload:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes
  isExternal: false
  name: IncludeScopes
  nameWithType: IConsoleLoggerSettings.IncludeScopes
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.IncludeScopes
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken*
  commentId: Overload:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken
  isExternal: false
  name: ChangeToken
  nameWithType: IConsoleLoggerSettings.ChangeToken
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.ChangeToken
- uid: Microsoft.Extensions.Primitives.IChangeToken
  commentId: T:Microsoft.Extensions.Primitives.IChangeToken
  parent: Microsoft.Extensions.Primitives
  isExternal: false
  name: IChangeToken
  nameWithType: IChangeToken
  fullName: Microsoft.Extensions.Primitives.IChangeToken
- uid: Microsoft.Extensions.Primitives
  commentId: N:Microsoft.Extensions.Primitives
  isExternal: false
  name: Microsoft.Extensions.Primitives
  nameWithType: Microsoft.Extensions.Primitives
  fullName: Microsoft.Extensions.Primitives
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch*
  commentId: Overload:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch
  isExternal: false
  name: TryGetSwitch
  nameWithType: IConsoleLoggerSettings.TryGetSwitch
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.TryGetSwitch
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Extensions.Logging.LogLevel
  commentId: T:Microsoft.Extensions.Logging.LogLevel
  parent: Microsoft.Extensions.Logging
  isExternal: false
  name: LogLevel
  nameWithType: LogLevel
  fullName: Microsoft.Extensions.Logging.LogLevel
- uid: Microsoft.Extensions.Logging
  commentId: N:Microsoft.Extensions.Logging
  isExternal: false
  name: Microsoft.Extensions.Logging
  nameWithType: Microsoft.Extensions.Logging
  fullName: Microsoft.Extensions.Logging
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload*
  commentId: Overload:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload
  isExternal: false
  name: Reload
  nameWithType: IConsoleLoggerSettings.Reload
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings.Reload
- uid: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  commentId: T:Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
  parent: Microsoft.Extensions.Logging.Console
  isExternal: false
  name: IConsoleLoggerSettings
  nameWithType: IConsoleLoggerSettings
  fullName: Microsoft.Extensions.Logging.Console.IConsoleLoggerSettings
shouldSkipMarkup: true
