### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory
  commentId: T:Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory
  id: IApplicationBuilderFactory
  parent: Microsoft.AspNetCore.Hosting.Builder
  children:
  - Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder(Microsoft.AspNetCore.Http.Features.IFeatureCollection)
  langs:
  - csharp
  - vb
  name: IApplicationBuilderFactory
  nameWithType: IApplicationBuilderFactory
  fullName: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory
  type: Interface
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Builder/IApplicationBuilderFactory.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: IApplicationBuilderFactory
    path: src/Microsoft.AspNetCore.Hosting/Builder/IApplicationBuilderFactory.cs
    startLine: 8
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Builder
  syntax:
    content: public interface IApplicationBuilderFactory
    content.vb: Public Interface IApplicationBuilderFactory
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder(Microsoft.AspNetCore.Http.Features.IFeatureCollection)
  commentId: M:Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder(Microsoft.AspNetCore.Http.Features.IFeatureCollection)
  id: CreateBuilder(Microsoft.AspNetCore.Http.Features.IFeatureCollection)
  parent: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory
  langs:
  - csharp
  - vb
  name: CreateBuilder(IFeatureCollection)
  nameWithType: IApplicationBuilderFactory.CreateBuilder(IFeatureCollection)
  fullName: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder(Microsoft.AspNetCore.Http.Features.IFeatureCollection)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Builder/IApplicationBuilderFactory.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: CreateBuilder
    path: src/Microsoft.AspNetCore.Hosting/Builder/IApplicationBuilderFactory.cs
    startLine: 10
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Builder
  syntax:
    content: IApplicationBuilder CreateBuilder(IFeatureCollection serverFeatures)
    content.vb: Function CreateBuilder(serverFeatures As IFeatureCollection) As IApplicationBuilder
    parameters:
    - id: serverFeatures
      type: Microsoft.AspNetCore.Http.Features.IFeatureCollection
    return:
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
  overload: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder*
references:
- uid: Microsoft.AspNetCore.Hosting.Builder
  commentId: N:Microsoft.AspNetCore.Hosting.Builder
  isExternal: false
  name: Microsoft.AspNetCore.Hosting.Builder
  nameWithType: Microsoft.AspNetCore.Hosting.Builder
  fullName: Microsoft.AspNetCore.Hosting.Builder
- uid: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder
  isExternal: false
  name: CreateBuilder
  nameWithType: IApplicationBuilderFactory.CreateBuilder
  fullName: Microsoft.AspNetCore.Hosting.Builder.IApplicationBuilderFactory.CreateBuilder
- uid: Microsoft.AspNetCore.Http.Features.IFeatureCollection
  commentId: T:Microsoft.AspNetCore.Http.Features.IFeatureCollection
  parent: Microsoft.AspNetCore.Http.Features
  isExternal: false
  name: IFeatureCollection
  nameWithType: IFeatureCollection
  fullName: Microsoft.AspNetCore.Http.Features.IFeatureCollection
- uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
  commentId: T:Microsoft.AspNetCore.Builder.IApplicationBuilder
  parent: Microsoft.AspNetCore.Builder
  isExternal: false
  name: IApplicationBuilder
  nameWithType: IApplicationBuilder
  fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
- uid: Microsoft.AspNetCore.Http.Features
  commentId: N:Microsoft.AspNetCore.Http.Features
  isExternal: false
  name: Microsoft.AspNetCore.Http.Features
  nameWithType: Microsoft.AspNetCore.Http.Features
  fullName: Microsoft.AspNetCore.Http.Features
- uid: Microsoft.AspNetCore.Builder
  commentId: N:Microsoft.AspNetCore.Builder
  isExternal: false
  name: Microsoft.AspNetCore.Builder
  nameWithType: Microsoft.AspNetCore.Builder
  fullName: Microsoft.AspNetCore.Builder
shouldSkipMarkup: true
