### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder
  commentId: T:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder
  id: ConfigureBuilder
  parent: Microsoft.AspNetCore.Hosting.Internal
  children:
  - Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.#ctor(System.Reflection.MethodInfo)
  - Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build(System.Object)
  - Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo
  langs:
  - csharp
  - vb
  name: ConfigureBuilder
  nameWithType: ConfigureBuilder
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: ConfigureBuilder
    path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
    startLine: 10
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public class ConfigureBuilder
    content.vb: Public Class ConfigureBuilder
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.#ctor(System.Reflection.MethodInfo)
  commentId: M:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.#ctor(System.Reflection.MethodInfo)
  id: '#ctor(System.Reflection.MethodInfo)'
  parent: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder
  langs:
  - csharp
  - vb
  name: ConfigureBuilder(MethodInfo)
  nameWithType: ConfigureBuilder.ConfigureBuilder(MethodInfo)
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.ConfigureBuilder(System.Reflection.MethodInfo)
  type: Constructor
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: .ctor
    path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
    startLine: 12
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public ConfigureBuilder(MethodInfo configure)
    content.vb: Public Sub New(configure As MethodInfo)
    parameters:
    - id: configure
      type: System.Reflection.MethodInfo
  overload: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo
  id: MethodInfo
  parent: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder
  langs:
  - csharp
  - vb
  name: MethodInfo
  nameWithType: ConfigureBuilder.MethodInfo
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: MethodInfo
    path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
    startLine: 17
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public MethodInfo MethodInfo { get; }
    content.vb: Public ReadOnly Property MethodInfo As MethodInfo
    parameters: []
    return:
      type: System.Reflection.MethodInfo
  overload: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build(System.Object)
  commentId: M:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build(System.Object)
  id: Build(System.Object)
  parent: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder
  langs:
  - csharp
  - vb
  name: Build(Object)
  nameWithType: ConfigureBuilder.Build(Object)
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build(System.Object)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
    id: Build
    path: src/Microsoft.AspNetCore.Hosting/Internal/ConfigureBuilder.cs
    startLine: 19
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public Action<IApplicationBuilder> Build(object instance)
    content.vb: Public Function Build(instance As Object) As Action(Of IApplicationBuilder)
    parameters:
    - id: instance
      type: System.Object
    return:
      type: System.Action{Microsoft.AspNetCore.Builder.IApplicationBuilder}
  overload: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Microsoft.AspNetCore.Hosting.Internal
  commentId: N:Microsoft.AspNetCore.Hosting.Internal
  isExternal: false
  name: Microsoft.AspNetCore.Hosting.Internal
  nameWithType: Microsoft.AspNetCore.Hosting.Internal
  fullName: Microsoft.AspNetCore.Hosting.Internal
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.#ctor*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.#ctor
  isExternal: false
  name: ConfigureBuilder
  nameWithType: ConfigureBuilder.ConfigureBuilder
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.ConfigureBuilder
- uid: System.Reflection.MethodInfo
  commentId: T:System.Reflection.MethodInfo
  parent: System.Reflection
  isExternal: true
  name: MethodInfo
  nameWithType: MethodInfo
  fullName: System.Reflection.MethodInfo
- uid: System.Reflection
  commentId: N:System.Reflection
  isExternal: false
  name: System.Reflection
  nameWithType: System.Reflection
  fullName: System.Reflection
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo
  isExternal: false
  name: MethodInfo
  nameWithType: ConfigureBuilder.MethodInfo
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.MethodInfo
- uid: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build
  isExternal: false
  name: Build
  nameWithType: ConfigureBuilder.Build
  fullName: Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Build
- uid: System.Action{Microsoft.AspNetCore.Builder.IApplicationBuilder}
  commentId: T:System.Action{Microsoft.AspNetCore.Builder.IApplicationBuilder}
  parent: System
  definition: System.Action`1
  name: Action<IApplicationBuilder>
  nameWithType: Action<IApplicationBuilder>
  fullName: System.Action<Microsoft.AspNetCore.Builder.IApplicationBuilder>
  nameWithType.vb: Action(Of IApplicationBuilder)
  fullname.vb: System.Action(Of Microsoft.AspNetCore.Builder.IApplicationBuilder)
  name.vb: Action(Of IApplicationBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
    name: IApplicationBuilder
    nameWithType: IApplicationBuilder
    fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
    name: IApplicationBuilder
    nameWithType: IApplicationBuilder
    fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullname.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
shouldSkipMarkup: true
