### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
  commentId: T:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
  id: MvcApplicationBuilderExtensions
  parent: Microsoft.AspNetCore.Builder
  children:
  - Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder)
  - Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder,System.Action{IRouteBuilder})
  - Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute(IApplicationBuilder)
  langs:
  - csharp
  - vb
  name: MvcApplicationBuilderExtensions
  nameWithType: MvcApplicationBuilderExtensions
  fullName: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
  type: Class
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: MvcApplicationBuilderExtensions
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
    startLine: 14
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Builder
  summary: "\nExtension methods for <see cref=\"!:IApplicationBuilder\"></see> to add MVC to the request execution pipeline.\n"
  example: []
  syntax:
    content: public static class MvcApplicationBuilderExtensions
    content.vb: Public Module MvcApplicationBuilderExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder)
  commentId: M:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder)
  id: UseMvc(IApplicationBuilder)
  isExtensionMethod: true
  parent: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseMvc(IApplicationBuilder)
  nameWithType: MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder)
  fullName: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: UseMvc
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
    startLine: 23
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Builder
  summary: "\nAdds MVC to the <see cref=\"!:IApplicationBuilder\"></see> request execution pipeline.\n"
  remarks: >-
    This method only supports attribute routing. To add conventional routes use

    <xref href="Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder%2cSystem.Action%7bIRouteBuilder%7d)" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static IApplicationBuilder UseMvc(this IApplicationBuilder app)
    parameters:
    - id: app
      type: IApplicationBuilder
      description: The <see cref="!:IApplicationBuilder"></see>.
    return:
      type: IApplicationBuilder
      description: A reference to this instance after the operation has completed.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseMvc(app As IApplicationBuilder) As IApplicationBuilder
  overload: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute(IApplicationBuilder)
  commentId: M:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute(IApplicationBuilder)
  id: UseMvcWithDefaultRoute(IApplicationBuilder)
  isExtensionMethod: true
  parent: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseMvcWithDefaultRoute(IApplicationBuilder)
  nameWithType: MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute(IApplicationBuilder)
  fullName: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute(IApplicationBuilder)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: UseMvcWithDefaultRoute
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
    startLine: 42
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Builder
  summary: "\nAdds MVC to the <see cref=\"!:IApplicationBuilder\"></see> request execution pipeline\nwith a default route named &apos;default&apos; and the following template:\n&apos;{controller=Home}/{action=Index}/{id?}&apos;.\n"
  example: []
  syntax:
    content: public static IApplicationBuilder UseMvcWithDefaultRoute(this IApplicationBuilder app)
    parameters:
    - id: app
      type: IApplicationBuilder
      description: The <see cref="!:IApplicationBuilder"></see>.
    return:
      type: IApplicationBuilder
      description: A reference to this instance after the operation has completed.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseMvcWithDefaultRoute(app As IApplicationBuilder) As IApplicationBuilder
  overload: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder,System.Action{IRouteBuilder})
  commentId: M:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder,System.Action{IRouteBuilder})
  id: UseMvc(IApplicationBuilder,System.Action{IRouteBuilder})
  isExtensionMethod: true
  parent: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseMvc(IApplicationBuilder, Action<IRouteBuilder>)
  nameWithType: MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder, Action<IRouteBuilder>)
  fullName: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder, System.Action<IRouteBuilder>)
  type: Method
  source:
    remote:
      path: src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
      branch: master
      repo: https://github.com/aspnet/Mvc.git
    id: UseMvc
    path: ../aspnet/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Builder/MvcApplicationBuilderExtensions.cs
    startLine: 63
  assemblies:
  - Microsoft.AspNetCore.Mvc.Core
  namespace: Microsoft.AspNetCore.Builder
  summary: "\nAdds MVC to the <see cref=\"!:IApplicationBuilder\"></see> request execution pipeline.\n"
  example: []
  syntax:
    content: public static IApplicationBuilder UseMvc(this IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)
    parameters:
    - id: app
      type: IApplicationBuilder
      description: The <see cref="!:IApplicationBuilder"></see>.
    - id: configureRoutes
      type: System.Action{IRouteBuilder}
      description: A callback to configure MVC routes.
    return:
      type: IApplicationBuilder
      description: A reference to this instance after the operation has completed.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseMvc(app As IApplicationBuilder, configureRoutes As Action(Of IRouteBuilder)) As IApplicationBuilder
  overload: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc*
  nameWithType.vb: MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder, Action(Of IRouteBuilder))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder, System.Action(Of IRouteBuilder))
  name.vb: UseMvc(IApplicationBuilder, Action(Of IRouteBuilder))
references:
- uid: Microsoft.AspNetCore.Builder
  commentId: N:Microsoft.AspNetCore.Builder
  isExternal: false
  name: Microsoft.AspNetCore.Builder
  nameWithType: Microsoft.AspNetCore.Builder
  fullName: Microsoft.AspNetCore.Builder
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder,System.Action{IRouteBuilder})
  commentId: M:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder,System.Action{IRouteBuilder})
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc*
  commentId: Overload:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc
  isExternal: false
  name: UseMvc
  nameWithType: MvcApplicationBuilderExtensions.UseMvc
  fullName: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc
- uid: IApplicationBuilder
  isExternal: true
  name: IApplicationBuilder
  nameWithType: IApplicationBuilder
  fullName: IApplicationBuilder
- uid: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute*
  commentId: Overload:Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute
  isExternal: false
  name: UseMvcWithDefaultRoute
  nameWithType: MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute
  fullName: Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvcWithDefaultRoute
- uid: System.Action{IRouteBuilder}
  commentId: T:System.Action{IRouteBuilder}
  parent: System
  definition: System.Action`1
  name: Action<IRouteBuilder>
  nameWithType: Action<IRouteBuilder>
  fullName: System.Action<IRouteBuilder>
  nameWithType.vb: Action(Of IRouteBuilder)
  fullName.vb: System.Action(Of IRouteBuilder)
  name.vb: Action(Of IRouteBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: IRouteBuilder
    name: IRouteBuilder
    nameWithType: IRouteBuilder
    fullName: IRouteBuilder
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: IRouteBuilder
    name: IRouteBuilder
    nameWithType: IRouteBuilder
    fullName: IRouteBuilder
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
shouldSkipMarkup: true
