### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  id: Microsoft.Extensions.Configuration
  children:
  - Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions
  - Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
  - Microsoft.Extensions.Configuration.ConfigurationBinder
  - Microsoft.Extensions.Configuration.ConfigurationBuilder
  - Microsoft.Extensions.Configuration.ConfigurationExtensions
  - Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  - Microsoft.Extensions.Configuration.ConfigurationPath
  - Microsoft.Extensions.Configuration.ConfigurationProvider
  - Microsoft.Extensions.Configuration.ConfigurationReloadToken
  - Microsoft.Extensions.Configuration.ConfigurationRoot
  - Microsoft.Extensions.Configuration.ConfigurationSection
  - Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
  - Microsoft.Extensions.Configuration.FileConfigurationExtensions
  - Microsoft.Extensions.Configuration.FileConfigurationProvider
  - Microsoft.Extensions.Configuration.FileConfigurationSource
  - Microsoft.Extensions.Configuration.FileLoadExceptionContext
  - Microsoft.Extensions.Configuration.IConfiguration
  - Microsoft.Extensions.Configuration.IConfigurationBuilder
  - Microsoft.Extensions.Configuration.IConfigurationProvider
  - Microsoft.Extensions.Configuration.IConfigurationRoot
  - Microsoft.Extensions.Configuration.IConfigurationSection
  - Microsoft.Extensions.Configuration.IConfigurationSource
  - Microsoft.Extensions.Configuration.IniConfigurationExtensions
  - Microsoft.Extensions.Configuration.JsonConfigurationExtensions
  - Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  - Microsoft.Extensions.Configuration.XmlConfigurationExtensions
  langs:
  - csharp
  - vb
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
  type: Namespace
  assemblies:
  - Microsoft.Extensions.Configuration.Abstractions
references:
- uid: Microsoft.Extensions.Configuration.ConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.ConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ConfigurationPath
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationPath
  isExternal: false
  name: ConfigurationPath
  nameWithType: ConfigurationPath
  fullName: Microsoft.Extensions.Configuration.ConfigurationPath
- uid: Microsoft.Extensions.Configuration.IConfiguration
  commentId: T:Microsoft.Extensions.Configuration.IConfiguration
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: Microsoft.Extensions.Configuration.IConfiguration
- uid: Microsoft.Extensions.Configuration.IConfigurationBuilder
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationBuilder
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: Microsoft.Extensions.Configuration.IConfigurationBuilder
- uid: Microsoft.Extensions.Configuration.IConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.IConfigurationProvider
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationRoot
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationRoot
  nameWithType: IConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot
- uid: Microsoft.Extensions.Configuration.IConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSection
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationSection
  nameWithType: IConfigurationSection
  fullName: Microsoft.Extensions.Configuration.IConfigurationSection
- uid: Microsoft.Extensions.Configuration.IConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IConfigurationSource
  nameWithType: IConfigurationSource
  fullName: Microsoft.Extensions.Configuration.IConfigurationSource
- uid: Microsoft.Extensions.Configuration.ConfigurationBuilder
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationBuilder
  isExternal: false
  name: ConfigurationBuilder
  nameWithType: ConfigurationBuilder
  fullName: Microsoft.Extensions.Configuration.ConfigurationBuilder
- uid: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationKeyComparer
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationKeyComparer
  nameWithType: ConfigurationKeyComparer
  fullName: Microsoft.Extensions.Configuration.ConfigurationKeyComparer
- uid: Microsoft.Extensions.Configuration.ConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationProvider
  nameWithType: ConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.ConfigurationProvider
- uid: Microsoft.Extensions.Configuration.ConfigurationReloadToken
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationReloadToken
  isExternal: false
  name: ConfigurationReloadToken
  nameWithType: ConfigurationReloadToken
  fullName: Microsoft.Extensions.Configuration.ConfigurationReloadToken
- uid: Microsoft.Extensions.Configuration.ConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationRoot
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationRoot
  nameWithType: ConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.ConfigurationRoot
- uid: Microsoft.Extensions.Configuration.ConfigurationSection
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationSection
  isExternal: false
  name: ConfigurationSection
  nameWithType: ConfigurationSection
  fullName: Microsoft.Extensions.Configuration.ConfigurationSection
- uid: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  commentId: T:Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: MemoryConfigurationBuilderExtensions
  nameWithType: MemoryConfigurationBuilderExtensions
  fullName: Microsoft.Extensions.Configuration.MemoryConfigurationBuilderExtensions
- uid: Microsoft.Extensions.Configuration.FileConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: FileConfigurationExtensions
  nameWithType: FileConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.FileConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.FileConfigurationProvider
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationProvider
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: FileConfigurationProvider
  nameWithType: FileConfigurationProvider
  fullName: Microsoft.Extensions.Configuration.FileConfigurationProvider
- uid: Microsoft.Extensions.Configuration.FileConfigurationSource
  commentId: T:Microsoft.Extensions.Configuration.FileConfigurationSource
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: FileConfigurationSource
  nameWithType: FileConfigurationSource
  fullName: Microsoft.Extensions.Configuration.FileConfigurationSource
- uid: Microsoft.Extensions.Configuration.FileLoadExceptionContext
  commentId: T:Microsoft.Extensions.Configuration.FileLoadExceptionContext
  isExternal: false
  name: FileLoadExceptionContext
  nameWithType: FileLoadExceptionContext
  fullName: Microsoft.Extensions.Configuration.FileLoadExceptionContext
- uid: Microsoft.Extensions.Configuration.XmlConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.XmlConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: XmlConfigurationExtensions
  nameWithType: XmlConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.XmlConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.JsonConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.JsonConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: JsonConfigurationExtensions
  nameWithType: JsonConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.JsonConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: AzureKeyVaultConfigurationExtensions
  nameWithType: AzureKeyVaultConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.ConfigurationBinder
  commentId: T:Microsoft.Extensions.Configuration.ConfigurationBinder
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: ConfigurationBinder
  nameWithType: ConfigurationBinder
  fullName: Microsoft.Extensions.Configuration.ConfigurationBinder
- uid: Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
  commentId: T:Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: EnvironmentVariablesExtensions
  nameWithType: EnvironmentVariablesExtensions
  fullName: Microsoft.Extensions.Configuration.EnvironmentVariablesExtensions
- uid: Microsoft.Extensions.Configuration.IniConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.IniConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: IniConfigurationExtensions
  nameWithType: IniConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.IniConfigurationExtensions
- uid: Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
  commentId: T:Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
  parent: Microsoft.Extensions.Configuration
  isExternal: false
  name: CommandLineConfigurationExtensions
  nameWithType: CommandLineConfigurationExtensions
  fullName: Microsoft.Extensions.Configuration.CommandLineConfigurationExtensions
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: false
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
