### YamlMime:ManagedReference
items:
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context
  commentId: T:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context
  id: HostingApplication.Context
  parent: Microsoft.AspNetCore.Hosting.Internal
  children:
  - Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext
  - Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope
  - Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp
  langs:
  - csharp
  - vb
  name: HostingApplication.Context
  nameWithType: HostingApplication.Context
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context
  type: Struct
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
      commit: 873a0e7a7ffc5cdc991222913095d8c43c2d9eb6
    id: Context
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
    startLine: 92
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public struct Context
    content.vb: Public Structure Context
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext
  id: HttpContext
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context
  langs:
  - csharp
  - vb
  name: HttpContext
  nameWithType: HostingApplication.Context.HttpContext
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
      commit: 873a0e7a7ffc5cdc991222913095d8c43c2d9eb6
    id: HttpContext
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
    startLine: 94
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public HttpContext HttpContext { get; set; }
    content.vb: Public Property HttpContext As HttpContext
    parameters: []
    return:
      type: Microsoft.AspNetCore.Http.HttpContext
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope
  id: Scope
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context
  langs:
  - csharp
  - vb
  name: Scope
  nameWithType: HostingApplication.Context.Scope
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
      commit: 873a0e7a7ffc5cdc991222913095d8c43c2d9eb6
    id: Scope
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
    startLine: 95
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public IDisposable Scope { get; set; }
    content.vb: Public Property Scope As IDisposable
    parameters: []
    return:
      type: System.IDisposable
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp
  commentId: P:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp
  id: StartTimestamp
  parent: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context
  langs:
  - csharp
  - vb
  name: StartTimestamp
  nameWithType: HostingApplication.Context.StartTimestamp
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp
  type: Property
  source:
    remote:
      path: src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
      branch: master
      repo: https://github.com/aspnet/Hosting.git
      commit: 873a0e7a7ffc5cdc991222913095d8c43c2d9eb6
    id: StartTimestamp
    path: ../aspnet/Hosting/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs
    startLine: 96
  assemblies:
  - Microsoft.AspNetCore.Hosting
  namespace: Microsoft.AspNetCore.Hosting.Internal
  syntax:
    content: public long StartTimestamp { get; set; }
    content.vb: Public Property StartTimestamp As Long
    parameters: []
    return:
      type: System.Int64
  overload: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Microsoft.AspNetCore.Hosting.Internal
  commentId: N:Microsoft.AspNetCore.Hosting.Internal
  isExternal: false
  name: Microsoft.AspNetCore.Hosting.Internal
  nameWithType: Microsoft.AspNetCore.Hosting.Internal
  fullName: Microsoft.AspNetCore.Hosting.Internal
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  name: Equals(Object)
  nameWithType: ValueType.Equals(Object)
  fullName: System.ValueType.Equals(System.Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext
  isExternal: false
  name: HttpContext
  nameWithType: HostingApplication.Context.HttpContext
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.HttpContext
- uid: Microsoft.AspNetCore.Http.HttpContext
  commentId: T:Microsoft.AspNetCore.Http.HttpContext
  parent: Microsoft.AspNetCore.Http
  isExternal: false
  name: HttpContext
  nameWithType: HttpContext
  fullName: Microsoft.AspNetCore.Http.HttpContext
- uid: Microsoft.AspNetCore.Http
  commentId: N:Microsoft.AspNetCore.Http
  isExternal: false
  name: Microsoft.AspNetCore.Http
  nameWithType: Microsoft.AspNetCore.Http
  fullName: Microsoft.AspNetCore.Http
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope
  isExternal: false
  name: Scope
  nameWithType: HostingApplication.Context.Scope
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.Scope
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp*
  commentId: Overload:Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp
  isExternal: false
  name: StartTimestamp
  nameWithType: HostingApplication.Context.StartTimestamp
  fullName: Microsoft.AspNetCore.Hosting.Internal.HostingApplication.Context.StartTimestamp
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
shouldSkipMarkup: true
